### ISSUE TITLE
No +[RCTConvert MKCoordinateRegion:] function found.

### ISSUE THREAD

**Issue by james2406** [airbnb/react-native-maps#1287]
After upgrading to react-native: 0.44 from 0.43 I'm receiving the error:
`No +[RCTConvert MKCoordinateRegion:] function found.`

...and sometimes:
`Exception thrown while executing UI block: +[RCTConvert MKCoordinateRegion:]: unrecognized selector sent to class 0x1065686f8`

...when using react-native-maps.

I've looked through the 0.44 change log and can't see why this error has started occurring.

It's not too much of a problem as I can just esc the errors, but the region no longer aligns to the current location.

![screen shot 2017-05-01 at 13 11 41](https://cloud.githubusercontent.com/assets/10858584/25579428/c8dfa436-2e6f-11e7-9b54-b721070fb43c.png)
![screen shot 2017-05-01 at 13 12 32](https://cloud.githubusercontent.com/assets/10858584/25579441/dad26372-2e6f-11e7-979b-857a76db7ee0.png)

```
{
	"name": "trace",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"axios": "^0.16.1",
		"react": "16.0.0-alpha.6",
		"react-native": "0.44.0",
		"react-native-maps": "^0.14.0",
		"react-native-vector-icons": "^4.0.1",
		"react-navigation": "^1.0.0-beta.9",
		"react-redux": "^5.0.4",
		"redux": "^3.6.0",
		"redux-thunk": "^2.2.0"
	},
	"devDependencies": {
		"babel-jest": "19.0.0",
		"babel-plugin-module-resolver": "^2.7.0",
		"babel-preset-react-native": "1.9.1",
		"jest": "19.0.2",
		"react-test-renderer": "16.0.0-alpha.6"
	},
	"jest": {
		"preset": "react-native"
	}
}
```

**Comment by jeveloper** [comment]
I know that they removed MapView completely from RN in rn 44, perhaps this lib is relying on something that just doesnt exist anymore.

This would be good to know , if this lib for the moment isnt compatible with RN 44 @lelandrichardson  

Thanks

**Comment by henrikra** [comment]
Looks like there is 23 files that are still using MapKit which is removed from React Native 0.44 https://github.com/airbnb/react-native-maps/search?utf8=%E2%9C%93&q=MapKit&type=

It is so weird that React Native recommends to use this library and does not communicate to Airbnb guys that they are removing MapKit. Or maybe Airbnb did not care either way :/

**Comment by jeveloper** [comment]
That's not accurate @henrikra , RN 42 onwards specified they are deprecating mapview and everything related to it. Also few months back the roadmap included who is taking over the map , its this lib.

**Comment by henrikra** [comment]
@jeveloper So why this lib is still relying on MapKit?

**Comment by jeveloper** [comment]
I think Leland is too busy and this lib definitely needs more collaborators.
Its definitely behind RN

**Comment by guoliang1206** [comment]
At present, which map component can I use?

**Comment by Amurmurmur** [comment]
+1 Similiar issue here :/
Hope airbnb guys provide a support for RN 0.44.0 as soon as they can

**Comment by henrikra** [comment]
@Amurmurmur I agree since RN 0.44 fixes lots of bugs that are needed

**Comment by james2406** [comment]
It looks like a few commits were made to the master branch, which should fix the 0.44 issue https://github.com/airbnb/react-native-maps/commit/4b861c949a079a393f48a485943d3a506a151ac0

**Comment by grin** [comment]
I got it working on 0.44 with latest react-native-map master on iOS. I run into some errors while unlinking old libs, so I removed them manually and then re-added the new ones following these steps: https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md#option-3-manually

**Comment by henrikra** [comment]
I just tested and I can confirm that this is now fixed! This issue can be closed!

**Comment by npomfret** [comment]
I've pointed my package.json at master (`"react-native-maps": "https://github.com/airbnb/react-native-maps.git"`) but am still getting this error.  Have i missed something?

`192.168.1.75:8081/index.ios.bundle?platform=ios&dev=true&minify=false:13980 Exception thrown while executing UI block: +[RCTConvert MKCoordinateRegion:]: unrecognized selector sent to class 0x100dd5de8`

**Comment by henrikra** [comment]
@npomfret You have to relink with native ios files. Basically do manual installation of ios again https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md#option-3-manually

**Comment by guoliang1206** [comment]
@npomfret  I have do these things following：
1. use CocoaPods to link the react-native-maps on iOS project.
2. And I get a TransformError ,I have  install this `npm install --save-dev babel-plugin-module-resolver`
now I can run the map with RN 0.44
```
"dependencies": {
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "react-native-maps": "^0.14.0"
  },
  "devDependencies": {
    "babel-jest": "20.0.0",
    "babel-plugin-module-resolver": "^2.7.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "20.0.0",
    "react-test-renderer": "16.0.0-alpha.6"
  },
```

**Comment by npomfret** [comment]
Its working - thanks! I just had to delete the maps project from iOS and re-link for some reason

**Comment by henrikra** [comment]
Yeah I had to do the same thing :D Please close this @collabolators

**Comment by jeveloper** [comment]
FYI this should work with 0.15 version now

**Comment by Amurmurmur** [comment]
@jeveloper 
Still experiencing it on iOS :/

**Comment by jeveloper** [comment]
Do the cache reset, all those things

**Comment by Amurmurmur** [comment]
@jeveloper 
Did
```
watchman watch-del-all && rm -rf node_modules/ && npm cache clean && npm install && npm start -- --reset-cache
```

Getting this:
![simulator screen shot 9 may 2017 00 24 12](https://cloud.githubusercontent.com/assets/8608333/25826045/f52b1a14-344d-11e7-85e5-b2dc87562a43.png)

**Comment by henrikra** [comment]
@Amurmurmur Install to new project and then tell if it is still not working. You also did not tell what version you have.

**Comment by Amurmurmur** [comment]
@henrikra 
Very sorry, I just relinked the lib.
All works perfectly!
Thumbs up!
👍 👍 👍 👍 👍

**Comment by jeveloper** [comment]
ahh , fantastic, glad it all worked out man 
yes relinking is part of a good cleaning process

**Comment by bosung90** [comment]
Fixed it by running
`react-native unlink react-native-maps`
`react-native link react-native-maps`
Then remove any duplicated imports (if any)

**Comment by MyTotoro** [comment]
I'm still encountering the same issue (after reset cache / rm node modules / rm ios /build and restart and relinking)

![screen shot 2017-06-04 at 12 46 27 am](https://cloud.githubusercontent.com/assets/3621921/26759033/47fffd42-48bf-11e7-8fe4-3fe8d046076b.png)


![screen shot 2017-06-04 at 12 45 34 am](https://cloud.githubusercontent.com/assets/3621921/26759029/2cce2878-48bf-11e7-9d1d-44576acca1dd.png)

```
2017-06-04 00:41:30.081 [info][tid:main][NetworkManager.m:38] Error setting property 'region' of AIRMap with tag #77: Error setting property 'region' of AIRMap with tag #216: Error setting property 'region' of AIRMap with tag #492: Error setting property 'region' of AIRMap with tag #724: didReceiveResponse
```

I have a NativeModule `NetworkManager.m` that just does some simple HTTP requests - I get the same red error screens when I start the map and when I navigate to the map screen.

The `NetworkManager.m`:

```
- (void) URLSession:(NSURLSession *)session dataTask:(NSURLSessionDataTask *)dataTask didReceiveResponse:(NSURLResponse *)response completionHandler:(void (^)(NSURLSessionResponseDisposition))completionHandler
{
  RCTLogInfo(@"didReceiveResponse");
  completionHandler(NSURLSessionResponseAllow);
}
```

I don't get how this would overlap with AirMaps...

**Comment by kelset** [comment]
I think the issue may be caused by RN 0.45, there are no Release Notes yet. So I highly suggest you to roll back to 0.44.

**Comment by MobiusHorizons** [comment]
@kelset any progress on this? RN 0.46 is out now, and I had hoped to upgrade. Also if you can point me in the right direction, I would gladly PR.

**Comment by Amurmurmur** [comment]
@MobiusHorizons using it with RN 0.46.1 with no problems so far. both iOS and Android

**Comment by kelset** [comment]
@MobiusHorizons latest version works fine with me, probably you just need to re-link `react-native-maps`; try unlinking it, then updating, then relinking.

**Comment by MobiusHorizons** [comment]
ok, i've already reverted. I'll try it again if I get some time.

**Comment by aprihodko** [comment]
RN 0.46.4

Fixed it by running
react-native unlink react-native-maps
react-native link react-native-maps

**Comment by jomaint** [comment]
Was happening to me a few times for no reason. Tried everything mentioned above. Only fix is to start a new project or upgrade my react-native-maps from 0.16.2 to 0.16.4. Hope it helps someone :)

**Comment by G-Hexa** [comment]
RN 0.47.2
react-native-maps 0.16.4


It works perfectly with manual linking but I get this error after installing `react-native-maps` using CocoaPods in order to  provide Google Maps on IOS. All manual linking data and settings were removed from Xcode project. 

I'm don't have much experience in RN / CocoaPods / IOS and I'm maybe misunderstanding something, but it looks weird to me as far as CocoaPods is managing these dependencies.

**Comment by ShunYamada** [comment]
I would work today!

The error occurred just in iPhone(actually worked generally in Simulator on Mac), for me this is the problem shortage of `libAirMap.a` on Linked binary and `AirMap.xcodeproj` on Libraries.

After added, that would work.

**Comment by breadadams** [comment]
This popped up for me today whilst trying to get the lib to work.

Cleaning the project in Xcode (`Product → Clean`) & **relaunching Xcode** appears to have resolved it.
