### ISSUE TITLE
react-native-maps (0.13 and 0.14) does not work with RN0.44

### ISSUE THREAD

**Issue by npomfret** [airbnb/react-native-maps#1298]
I just tried an upgrade to RN 0.44 but so far have run into these 2 errors:

https://github.com/airbnb/react-native-maps/issues/1287
https://github.com/airbnb/react-native-maps/issues/1193

I guess this is the _official_ maps solution for react native now.  It's a shame that there's been a RN release and this hasn't been updated to be compatible.

@lelandrichardson @janicduplessis @davidstoker - would it be possible for someone to look into these?  Or if you guys are too busy maybe consider adding some more contributors?

**Comment by vjeranc** [comment]
It works if setup through Podfile.

**Comment by pfulop** [comment]
@vjeranc You mean option 1 from installation instructions? Because using that podfile from example just opens up doors to this bug https://github.com/facebook/react-native/issues/13198.

**Comment by vjeranc** [comment]
@pfulop Yes, it seems to be the case.

I've made a pull request https://github.com/facebook/react-native/pull/13785

**Comment by pfulop** [comment]
@vjeranc that worked with master branch. But for some reason it broke react-native-fetch-blob. So I just used master branch without modifying podfile and removed google maps. It works and I can wait a bit longer till gmaps will be fixed.
Thanks anyway

**Comment by nico1510** [comment]
For Mac users @vjeranc's command is ```sed -i '' 's/#import <RCTAnimation\/RCTValueAnimatedNode.h>/#import "RCTValueAnimatedNode.h"/' Libraries/NativeAnimation/RCTNativeAnimatedNodesManager.h```

**Comment by guoliang1206** [comment]
@nico1510  where to write these commands?

**Comment by nico1510** [comment]
inside node_modules/react-native

**Comment by guoliang1206** [comment]
@nico1510 Thank you, but  is it write in  package.json file?  And the maps version 0.14.0 use this command require install with CocoaPods?

**Comment by nico1510** [comment]
You could also add the command as a postinstall script in package.json so that it gets executed on every npm install but you don't have to if you can afford to wait for the next react native release where this should be fixed.

**Comment by gpedro** [comment]
@nico1510 this command solve that error? "
clang: error: no such file or directory: '/Users/gpedro/Development/react-native-app-demo/node_modules/react-native-maps/lib/ios/AirMaps/RCTConvert+MapKit.m'
clang: error: no input files
"

**Comment by nico1510** [comment]
No it's supposed to fix the ```'RCTAnimation/RCTValueAnimatedNode.h' file not found ``` error

**Comment by henrikra** [comment]
Now when taking latest version from master this works with RN 0.44

**Comment by npomfret** [comment]
For me master works for iOS but not android.  Have checked all the installation instructions (and updated by gradle stuff accordingly) but I'm still getting this error:

`Configuration with name 'default' not found.`

**Comment by henrikra** [comment]
No you havent. That error means that path to react-native-maps is wrong in `settings.gradle` file. Old path was `../node_modules/react-native-maps/android` and now it is `../node_modules/react-native-maps/lib/android`. I hope this helps :D

**Comment by npomfret** [comment]
Yep done that.  Deleted my node_modules, reinstalled etc - the files are there (in the lib dir) but still getting that error.

**Comment by henrikra** [comment]
Create fresh project and install react-native-maps and then tell the results

**Comment by npomfret** [comment]
I'm sure it works in a fresh project.  That's not my problem.  I'm trying to upgrade from 0.13 in my current project to master (because of the incompatibilities with RN0.44).  The latest commits fix the iOS build, but my android studio / gradle build refuses to acknowledge the move to the lib folder.

I can see the files, I've cleaned node_modules, the npm cache etc.

Removing the dependency on maps allows my project to compile, so I think it's definitely the maps project that's causing it, although the gradle error message isn't very helpful at all.

**Comment by henrikra** [comment]
Okay then this can be closed since it is project specific problem :)
